#define WINDOW_WIDTH  500
#define WINDOW_HEIGHT 500

#define GRID_WIDTH  900
#define GRID_HEIGHT 700
#define MENU_WIDTH 200

#define CELL_SIZE 25
#define MENU_FONT_SIZE 20
#define GRID_ROW (GRID_WIDTH / CELL_SIZE)
#define GRID_COL (GRID_HEIGHT / CELL_SIZE - 2)

#define MIN_WINDOW_WIDTH GRID_WIDTH + 2 * MENU_WIDTH
#define MIN_WINDOW_HEIGHT GRID_HEIGHT
#define DELAY 40

#define TERMINAL_SIZE 10
#define MAX_WIRE_PTS 50
